version: '3'
services:
  runner:
    command: python main.py --root=/dir
    build: ./
    environment:
    - OUT_PATH=/out
    - OUT_WIDTH=50
    - OUT_HEIGHT=20
    volumes:
    - ./app:/app
    - ./dir:/dir
    - ./out:/out
